### ISSUE TITLE
Add Relic helper as requested

### ISSUE THREAD

**Issue by snorux** [snooooowy/EurekaHelper#16]

**Comment by Hinalover** [comment]
The only enhancements I would request of this feature is if there is a way to highlight the bar in each of the tabs if the player has the item or higher. For example, I have the Hydatos Battleaxe +1 in my retainer. That means:
Anemos: Farsha, Farsha +1, Farsha +2, Farsha Anemos
Pagos: Farsha Pagos, Farsha Pagos +1, Elemental Battleaxe
Pyros: Elemental Battleaxe +1, Elemental Battleaxe +2, Pyros Battleaxe
Hydatos: Hydatos Battleaxe and Hydatos Battleaxe +1
Should all be highlighted.

**Comment by snorux** [comment]
> The only enhancements I would request of this feature is if there is a way to highlight the bar in each of the tabs if the player has the item or higher. For example, I have the Hydatos Battleaxe +1 in my retainer. That means: Anemos: Farsha, Farsha +1, Farsha +2, Farsha Anemos Pagos: Farsha Pagos, Farsha Pagos +1, Elemental Battleaxe Pyros: Elemental Battleaxe +1, Elemental Battleaxe +2, Pyros Battleaxe Hydatos: Hydatos Battleaxe and Hydatos Battleaxe +1 Should all be highlighted.

Hi, this is currently not planned as it would mean tracking all of the relic items. Though in the future, I might include an option that will allow you to mark each relic as complete
