### ISSUE TITLE
add auto-create tracker when entering eureka instance, and print to chat tracker link or open main plugin window button

### ISSUE THREAD

**Issue by Otaku-2** [snooooowy/EurekaHelper#17]

**Comment by snorux** [comment]
Proposed solution:

1. User instances into a eureka zone
2. Check if user is already connected to tracker
3. If not connected, auto create a new tracker. If connected, ignore

**Comment by snorux** [comment]
Completed in d68781c0f41fa1b843582052d0e4e16ca18cba14

Merged to plugin master, please update to version 1.3.1.2. Open the issue again if you encounter any issues.
