### ISSUE TITLE
wrong reagion for the tracker

### ISSUE THREAD

**Issue by JaideAirblade** [snooooowy/EurekaHelper#2]
sets the region for the tracker as [中国区 (couldnt reproduce it yet)

**Comment by snorux** [comment]
Hi, can I get more information (e.g What world are you in)? Setting the tracker to public should take the current datacenter world you're in and set it using that value.

**Comment by JaideAirblade** [comment]
on light and it does it always wen seting it to public and also searches for the same server for trackers

**Comment by snorux** [comment]
Seems like the datacenter id in-game doesn't match the datacenter id needed in ffxiv-eureka.com. Will fix it in the next version (in-progress).

**Comment by snorux** [comment]
This should be fixed in the new 0.0.0.3 release that was merged today. 

Will be closing this issue, please reopen if it doesn't work
