### ISSUE TITLE
Incorrect Value in Relic Helper

### ISSUE THREAD

**Issue by jadealt3** [snooooowy/EurekaHelper#28]
Under Relic/Pagos/Elemental, it incorrectly says only 10 frosted protean crystals are needed. It should say 16.
![image](https://github.com/snooooowy/EurekaHelper/assets/102472332/cda837ba-2208-4b71-b59a-e3eb7879f7c5)
![Screenshot_1](https://github.com/snooooowy/EurekaHelper/assets/102472332/99468c2a-caa7-468e-9b4e-14690021cb7e)

**Comment by snorux** [comment]
Thank you for noticing it, I have pushed a fix to the incorrect requirement.

It will be pushed out in the next release
