### ISSUE TITLE
Not sure where to put this but something popped up lol about a fairy pos

### ISSUE THREAD

**Issue by VallyP** [snooooowy/EurekaHelper#32]
T: 795 X: 423.8157 Y: 661.35266 Z: -212.1115
New elemental found thing

**Comment by snorux** [comment]
Thank you~! You can add Elemental position in [this](https://github.com/snooooowy/EurekaHelper/issues/13) issue thread in the future 😄

**Comment by snorux** [comment]
Added in 1.6.1.7
