### ISSUE TITLE
Click to Copy no longer working

### ISSUE THREAD

**Issue by NCC-Lykos** [snooooowy/EurekaHelper#38]
1.5.2.0 - Using with Chat2 - Click to copy no longer working, doesn't copy anything to clipboard.

**Comment by snorux** [comment]
Hi, I believe it's due to this issue in ChatTwo. https://www.github.com/lojewalo/plugin-issues/issues/90

**Comment by snorux** [comment]
This should be fixed with the latest version of Chat2. I will proceed to close this issue.
