### ISSUE TITLE
Alarm notification for NM weather/time conditions

### ISSUE THREAD

**Issue by Dedoooo** [snooooowy/EurekaHelper#5]
Would be great to have options to choose alarms when conditions are about to be ready

**Comment by snorux** [comment]
Hmmm, I agree it would be nice feature to have. However, I'm not certain on how the implementation would be like.
I'll make something up in the future, no ETA as of now though.

**Comment by snorux** [comment]
Apologies for the wait, should be completed soon, got all the core features done. It's testing time
![image](https://user-images.githubusercontent.com/34697265/236858766-5404f20b-ec5d-4e45-b14b-dc2f383a7324.png)
![image](https://user-images.githubusercontent.com/34697265/236866439-f598e8c5-b8a2-4421-bc38-015041da26f0.png)

**Comment by Dedoooo** [comment]
Looks incredibly nice and simple

**Comment by 0x526f6d656f** [comment]
Looks like an amazing addition

**Comment by snorux** [comment]
This has been implemented and is now live.
Please update to v1.5.0.0 to get this feature.

I'll be closing this issue, please reopen if there are any bugs
