### ISSUE TITLE
Allow custom shout message

### ISSUE THREAD

**Issue by imvaskel** [snooooowy/EurekaHelper#6]
See title. I think that you should be able to set your own shout message (with formatters, i.e %boss or something around those lines replaces with the boss name) to allow people to put a bit of personality in their pop messages

**Comment by snorux** [comment]
Thank you for the suggestion, this is planned in the next release.

**Comment by snorux** [comment]
This has been implemented in version 0.0.0.6. Feel free to open this issue again if you encounter any issues
