### ISSUE TITLE
Add an option to randomize flag coordinates

### ISSUE THREAD

**Issue by snorux** [snooooowy/EurekaHelper#8]
To prevent identification of plugin users, add a configuration to randomize flag coordinates (enabled by default)

**Comment by snorux** [comment]
Implemented in b2d3da74cead5ffb4cc50d472f7036dee30a072a. Pushed to testing in version 0.0.0.7

**Comment by fallboo** [comment]
Need to do something like a minimum timer before shouting if you don't already. 
Some datacentres are mass-reporting everybody shouting within a second or two since it's seen as toxic to their communities.
